<a href="https://colab.research.google.com/github/Thisuka1103/Statistical-Learning-e22358/blob/main/Assignment%204/Data_Wrangling_Tested_Sample_E_22_358_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**1. Initialization**

In [1]:
!pip install git+https://github.com/Thisuka1103/Data-Analysis-Toolkit.git

Collecting git+https://github.com/Thisuka1103/Data-Analysis-Toolkit.git
  Cloning https://github.com/Thisuka1103/Data-Analysis-Toolkit.git to /tmp/pip-req-build-o65bywia
  Running command git clone --filter=blob:none --quiet https://github.com/Thisuka1103/Data-Analysis-Toolkit.git /tmp/pip-req-build-o65bywia
  Resolved https://github.com/Thisuka1103/Data-Analysis-Toolkit.git to commit 90ebacce7cd23c2a323a77b99771c9a9e65763ab
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from data_analysis==0.1.0) (2.2.2)
Requirement already satisfied: numpy<2 in /usr/local/lib/python3.12/dist-packages (from data_analysis==0.1.0) (1.26.4)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from data_analysis==0.1.0) (5.24.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from data_analysis==0.1.0) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from data_analysis==0.1.0) (1.6.1)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from data_analysis==0.1.0) (7.34.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython->data_analysis==0.1.0) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython->data_analysis==0.1.0) (0.20.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->data_analysis==0.1.0) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->data_analysis==0.1.0) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->data_analysis==0.1.0) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->data_analysis==0.1.0) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->data_analysis==0.1.0) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->data_analysis==0.1.0) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->data_analysis==0.1.0) (0.2.2)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->data_analysis==0.1.0) (4.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->data_analysis==0.1.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->data_analysis==0.1.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->data_analysis==0.1.0) (2026.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->data_analysis==0.1.0) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly->data_analysis==0.1.0) (26.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->data_analysis==0.1.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->data_analysis==0.1.0) (3.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->data_analysis==0.1.0) (0.8.7)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->data_analysis==0.1.0) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->data_analysis==0.1.0) (0.7.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->data_analysis==0.1.0) (1.17.0)

#**2. Data Ingestion**

In [2]:
from data_analysis import DataInspector, PlottingMethods

inspector = DataInspector()
PLT = PlottingMethods()

print("✅ Ready")

✅ Ready

#**3. Upload Data**

In [3]:
#inspector.upload_data()
inspector.load_from_path("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
# or from path
# inspector.load_from_path('/content/your_file.csv')

✅ Loaded 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv': 891 rows × 12 columns

#**4. Structural Analysis**

In [4]:
inspector.get_summary()

--- Data Summary ---
Rows: 891 | Columns: 12
Numerical (7): ['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
Categorical (5): ['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C

In [5]:
inspector.column_details()

🔹 PassengerId (Numeric): Range [1 to 891]
🔹 Survived (Numeric): Range [0 to 1]
🔹 Pclass (Numeric): Range [1 to 3]
🔸 Name (Categorical): 891 unique values
🔸 Sex (Categorical): 2 unique values
🔹 Age (Numeric): Range [0.42 to 80.0]
🔹 SibSp (Numeric): Range [0 to 8]
🔹 Parch (Numeric): Range [0 to 6]
🔸 Ticket (Categorical): 681 unique values
🔹 Fare (Numeric): Range [0.0 to 512.3292]
🔸 Cabin (Categorical): 147 unique values
🔸 Embarked (Categorical): 3 unique values

In [6]:
inspector.get_categorical_summary()

--- Categorical Deep Dive ---

         unique                      top freq
Name        891  Braund, Mr. Owen Harris    1
Sex           2                     male  577
Ticket      681                   347082    7
Cabin       147                  B96 B98    4
Embarked      3                        S  644

In [7]:
inspector.show_missing_data()

Found 708 rows with missing values:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

#**5. Data Cleaning**

In [8]:
inspector.remove_duplicates()

inspector.show_missing_data()

Removed 0 duplicate rows. New row count: 891
Found 708 rows with missing values:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [9]:
inspector.handle_missing_values(strategy='median')
inspector.handle_missing_values(strategy='mode')

# verify
inspector.show_missing_data()

🛠️ Imputation complete using 'median' strategy for: ['Age', 'Cabin', 'Embarked']
🛠️ Imputation complete using 'mode' strategy for: ['Cabin', 'Embarked']
No missing data found!

In [10]:
# inspect first
inspector.handle_outliers(find_and_delete=False)

🚨 PassengerId: Found 0 outliers.
🚨 Survived: Found 0 outliers.
🚨 Pclass: Found 0 outliers.
🚨 Age: Found 66 outliers.
🚨 SibSp: Found 46 outliers.
🚨 Parch: Found 213 outliers.
🚨 Fare: Found 116 outliers.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,B96 B98,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,B96 B98,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,B96 B98,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,B96 B98,Q
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,B96 B98,S

In [ ]:
# after reviewing, delete
inspector.handle_outliers(find_and_delete=True)

# or target specific columns only
# inspector.handle_outliers(columns=['col1', 'col2'], find_and_delete=True)

In [ ]:
inspector.delete_rows()
# enter comma separated row indices when prompted

In [ ]:
inspector.delete_columns()
# enter comma separated column names when prompted

#**6. Feature Engineering & Normalization**

In [11]:
numeric_df = inspector.extract_numeric_data()
display(numeric_df.head())

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0            1         0       3  22.0      1      0   7.2500
1            2         1       1  38.0      1      0  71.2833
2            3         1       3  26.0      0      0   7.9250
3            4         1       1  35.0      1      0  53.1000
4            5         0       3  35.0      0      0   8.0500

In [12]:
categorical_df = inspector.extract_categorical_data()
display(categorical_df.head())

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,B96 B98,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,B96 B98,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,B96 B98,S

In [13]:
# choose one: 'minmax', 'standard', 'robust'
numeric_normalized = inspector.extract_normalized_numeric_data(method='minmax')
display(numeric_normalized.head())

✨ Successfully scaled numerical data using the 'minmax' method.

   PassengerId  Survived  Pclass       Age  SibSp  Parch      Fare
0     0.000000       0.0     1.0  0.271174  0.125    0.0  0.014151
1     0.001124       1.0     0.0  0.472229  0.125    0.0  0.139136
2     0.002247       1.0     1.0  0.321438  0.000    0.0  0.015469
3     0.003371       1.0     0.0  0.434531  0.125    0.0  0.103644
4     0.004494       0.0     1.0  0.434531  0.000    0.0  0.015713

In [14]:
# choose one: 'onehot', 'ordinal', 'uniform', 'minmax_ordinal'
categorical_encoded = inspector.extract_normalized_categorical_data(method='onehot')
display(categorical_encoded.head())

✨ Successfully encoded categorical data using the 'onehot' method.

,"Name_Abbing, Mr. Anthony","Name_Abbott, Mr. Rossmore Edward","Name_Abbott, Mrs. Stanton (Rosa Hunt)","Name_Abelson, Mr. Samuel","Name_Abelson, Mrs. Samuel (Hannah Wizosky)","Name_Adahl, Mr. Mauritz Nils Martin","Name_Adams, Mr. John","Name_Ahlin, Mrs. Johan (Johanna Persdotter Larsson)","Name_Aks, Mrs. Sam (Leah Rosen)","Name_Albimona, Mr. Nassef Cassem",...,Cabin_F G73,Cabin_F2,Cabin_F33,Cabin_F38,Cabin_F4,Cabin_G6,Cabin_T,Embarked_C,Embarked_Q,Embarked_S
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [15]:
full_normalized = inspector.create_normalized_data_df()
display(full_normalized.head())
print(f"Shape: {full_normalized.shape}")

✨ Successfully encoded categorical data using the 'uniform' method.
✅ Success! Created merged DataFrame with 12 columns.

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Name,Sex,Ticket,Cabin,Embarked
0,1,0,3,22.0,1,0,7.2500,0.121348,1.0,0.769118,0.321918,1.0
1,2,1,1,38.0,1,0,71.2833,0.213483,0.0,0.876471,0.554795,0.0
2,3,1,3,26.0,0,0,7.9250,0.396629,0.0,0.983824,0.321918,1.0
3,4,1,1,35.0,1,0,53.1000,0.305618,0.0,0.072059,0.376712,1.0
4,5,0,3,35.0,0,0,8.0500,0.016854,1.0,0.694118,0.321918,1.0

Shape: (891, 12)

#**7. Visualization**

In [16]:
numeric_cols = inspector.df.select_dtypes(include='number').columns.tolist()
print(f"Numeric columns: {numeric_cols}")

inspector.plot_numerical(numeric_cols)

Numeric columns: ['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [17]:
cat_cols = inspector.df.select_dtypes(exclude='number').columns.tolist()
print(f"Categorical columns: {cat_cols}")

inspector.plot_categorical(cat_cols)

Categorical columns: ['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

In [18]:
all_cols = inspector.df.columns.tolist()
print(f"Available columns: {all_cols}")

# replace with any two columns from your dataset
col1 = all_cols[0]
col2 = all_cols[1]

inspector.plot_relationship(col1, col2)

Available columns: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

#**8. Correlation & Association**

In [19]:
inspector.plot_numerical_correlation()

In [20]:
inspector.plot_categorical_correlation()

--- Cramér's V Association Matrix ---

          Name    Sex  Ticket  Cabin  Embarked
Name       1.0  1.000   1.000  1.000     1.000
Sex        1.0  1.000   0.860  0.451     0.120
Ticket     1.0  0.860   1.000  0.918     0.998
Cabin      1.0  0.451   0.918  1.000     0.463
Embarked   1.0  0.120   0.998  0.463     1.000

          Name       Sex    Ticket     Cabin  Embarked
Name       1.0  1.000000  1.000000  1.000000  1.000000
Sex        1.0  1.000000  0.859783  0.451311  0.120404
Ticket     1.0  0.859783  1.000000  0.918447  0.997810
Cabin      1.0  0.451311  0.918447  1.000000  0.463047
Embarked   1.0  0.120404  0.997810  0.463047  1.000000

In [21]:
assoc_table = inspector.correlate_num_to_cat()
display(assoc_table)

/usr/local/lib/python3.12/dist-packages/scipy/stats/_axis_nan_policy.py:573: SmallSampleWarning:

all input arrays have length 1.  f_oneway requires that at least one input has length greater than 1.

/usr/local/lib/python3.12/dist-packages/data_analysis/core.py:666: SmallSampleWarning:

One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.

/usr/local/lib/python3.12/dist-packages/scipy/stats/_axis_nan_policy.py:573: SmallSampleWarning:

all input arrays have length 1.  f_oneway requires that at least one input has length greater than 1.

/usr/local/lib/python3.12/dist-packages/data_analysis/core.py:666: SmallSampleWarning:

One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.

/usr/local/lib/python3.12/dist-packages/scipy/stats/_axis_nan_policy.py:573: SmallSampleWarning:

all input arrays have length 1.  f_oneway requires that at least one input has length greater than 1.

/usr/local/lib/python3.12/dist-packages/data_analysis/core.py:666: SmallSampleWarning:

One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.

/usr/local/lib/python3.12/dist-packages/scipy/stats/_axis_nan_policy.py:573: SmallSampleWarning:

all input arrays have length 1.  f_oneway requires that at least one input has length greater than 1.

/usr/local/lib/python3.12/dist-packages/data_analysis/core.py:666: SmallSampleWarning:

One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.

/usr/local/lib/python3.12/dist-packages/scipy/stats/_axis_nan_policy.py:573: SmallSampleWarning:

all input arrays have length 1.  f_oneway requires that at least one input has length greater than 1.

/usr/local/lib/python3.12/dist-packages/data_analysis/core.py:666: SmallSampleWarning:

One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.

/usr/local/lib/python3.12/dist-packages/scipy/stats/_axis_nan_policy.py:573: SmallSampleWarning:

all input arrays have length 1.  f_oneway requires that at least one input has length greater than 1.

/usr/local/lib/python3.12/dist-packages/data_analysis/core.py:666: SmallSampleWarning:

One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.

/usr/local/lib/python3.12/dist-packages/scipy/stats/_axis_nan_policy.py:573: SmallSampleWarning:

all input arrays have length 1.  f_oneway requires that at least one input has length greater than 1.

/usr/local/lib/python3.12/dist-packages/data_analysis/core.py:666: SmallSampleWarning:

One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.

/usr/local/lib/python3.12/dist-packages/scipy/stats/_axis_nan_policy.py:579: ConstantInputWarning:

Each of the input arrays is constant; the F statistic is not defined or infinite

   Categorical    Numerical                     Type  Correlation  P-Value
0         Name  PassengerId  Eta (Multi-class ANOVA)        1.000      NaN
1         Name     Survived  Eta (Multi-class ANOVA)        1.000      NaN
2         Name       Pclass  Eta (Multi-class ANOVA)        1.000      NaN
3         Name          Age  Eta (Multi-class ANOVA)        1.000      NaN
4         Name        SibSp  Eta (Multi-class ANOVA)        1.000      NaN
5         Name        Parch  Eta (Multi-class ANOVA)        1.000      NaN
6         Name         Fare  Eta (Multi-class ANOVA)        1.000      NaN
7          Sex  PassengerId  Point-Biserial (Binary)        0.043   0.2004
8          Sex     Survived  Point-Biserial (Binary)       -0.543   0.0000
9          Sex       Pclass  Point-Biserial (Binary)        0.132   0.0001
10         Sex          Age  Point-Biserial (Binary)        0.081   0.0154
11         Sex        SibSp  Point-Biserial (Binary)       -0.115   0.0006
12         Sex        Parch  Point-Biserial (Binary)       -0.245   0.0000
13         Sex         Fare  Point-Biserial (Binary)       -0.182   0.0000
14      Ticket  PassengerId  Eta (Multi-class ANOVA)        0.876   0.4527
15      Ticket     Survived  Eta (Multi-class ANOVA)        0.928   0.0000
16      Ticket       Pclass  Eta (Multi-class ANOVA)        1.000   0.0000
17      Ticket          Age  Eta (Multi-class ANOVA)        0.879   0.3556
18      Ticket        SibSp  Eta (Multi-class ANOVA)        0.948   0.0000
19      Ticket        Parch  Eta (Multi-class ANOVA)        0.906   0.0013
20      Ticket         Fare  Eta (Multi-class ANOVA)        1.000   0.0000
21       Cabin  PassengerId  Eta (Multi-class ANOVA)        0.417   0.2793
22       Cabin     Survived  Eta (Multi-class ANOVA)        0.511   0.0000
23       Cabin       Pclass  Eta (Multi-class ANOVA)        0.774   0.0000
24       Cabin          Age  Eta (Multi-class ANOVA)        0.560   0.0000
25       Cabin        SibSp  Eta (Multi-class ANOVA)        0.264   1.0000
26       Cabin        Parch  Eta (Multi-class ANOVA)        0.399   0.6038
27       Cabin         Fare  Eta (Multi-class ANOVA)        0.816   0.0000
28    Embarked  PassengerId  Eta (Multi-class ANOVA)        0.034   0.5950
29    Embarked     Survived  Eta (Multi-class ANOVA)        0.171   0.0000
30    Embarked       Pclass  Eta (Multi-class ANOVA)        0.307   0.0000
31    Embarked          Age  Eta (Multi-class ANOVA)        0.041   0.4790
32    Embarked        SibSp  Eta (Multi-class ANOVA)        0.069   0.1176
33    Embarked        Parch  Eta (Multi-class ANOVA)        0.085   0.0414
34    Embarked         Fare  Eta (Multi-class ANOVA)        0.280   0.0000

In [22]:
inspector.plot_all_associations_heatmap()

--- Global Association Matrix ---

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,1.000,0.005,0.035,1.0,0.043,0.034,0.058,0.002,0.876,0.013,0.417,0.034
Survived,0.005,1.000,0.338,1.0,0.543,0.065,0.035,0.082,0.928,0.257,0.511,0.171
Pclass,0.035,0.338,1.000,1.0,0.132,0.340,0.083,0.018,1.000,0.549,0.774,0.307
Name,1.000,1.000,1.000,1.0,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
Sex,0.043,0.543,0.132,1.0,1.000,0.081,0.115,0.245,0.860,0.182,0.451,0.120
Age,0.034,0.065,0.340,1.0,0.081,1.000,0.233,0.172,0.879,0.097,0.560,0.041
SibSp,0.058,0.035,0.083,1.0,0.115,0.233,1.000,0.415,0.948,0.160,0.264,0.069
Parch,0.002,0.082,0.018,1.0,0.245,0.172,0.415,1.000,0.906,0.216,0.399,0.085
Ticket,0.876,0.928,1.000,1.0,0.860,0.879,0.948,0.906,1.000,1.000,0.918,0.998
Fare,0.013,0.257,0.549,1.0,0.182,0.097,0.160,0.216,1.000,1.000,0.816,0.280
Cabin,0.417,0.511,0.774,1.0,0.451,0.560,0.264,0.399,0.918,0.816,1.000,0.463
Embarked,0.034,0.171,0.307,1.0,0.120,0.041,0.069,0.085,0.998,0.280,0.463,1.000

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,1.000,0.005,0.035,1.0,0.043,0.034,0.058,0.002,0.876,0.013,0.417,0.034
Survived,0.005,1.000,0.338,1.0,0.543,0.065,0.035,0.082,0.928,0.257,0.511,0.171
Pclass,0.035,0.338,1.000,1.0,0.132,0.340,0.083,0.018,1.000,0.549,0.774,0.307
Name,1.000,1.000,1.000,1.0,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000
Sex,0.043,0.543,0.132,1.0,1.000,0.081,0.115,0.245,0.860,0.182,0.451,0.120
Age,0.034,0.065,0.340,1.0,0.081,1.000,0.233,0.172,0.879,0.097,0.560,0.041
SibSp,0.058,0.035,0.083,1.0,0.115,0.233,1.000,0.415,0.948,0.160,0.264,0.069
Parch,0.002,0.082,0.018,1.0,0.245,0.172,0.415,1.000,0.906,0.216,0.399,0.085
Ticket,0.876,0.928,1.000,1.0,0.860,0.879,0.948,0.906,1.000,1.000,0.918,0.998
Fare,0.013,0.257,0.549,1.0,0.182,0.097,0.160,0.216,1.000,1.000,0.816,0.280
Cabin,0.417,0.511,0.774,1.0,0.451,0.560,0.264,0.399,0.918,0.816,1.000,0.463
Embarked,0.034,0.171,0.307,1.0,0.120,0.041,0.069,0.085,0.998,0.280,0.463,1.000

#**9. Custom plotting**

In [ ]:
response = PLT.get_methods_info()
for method in response['response']:
    print(f"Method : {method['method']}")
    print(f"Signature : {method['signature']}")
    print(f"Description: {method['description']}")
    print("-" * 60)

In [ ]:
import json

data = json.dumps({"records": [
    {"category": "A", "value": 40},
    {"category": "B", "value": 60},
    {"category": "C", "value": 25}
]})

result = PLT.plot_bar_chart(x='category', y='value', title='Bar Chart', data=data)
PLT.display_image(result)

In [ ]:
result = PLT.plot_pie_chart(names='category', values='value', title='Pie Chart', data=data)
PLT.display_image(result)

In [ ]:
data_hist = json.dumps({"records": [
    {"value": v} for v in inspector.df.select_dtypes(include='number').iloc[:, 0].dropna().tolist()
]})

result = PLT.plot_histogram(x='value', title='Histogram', data=data_hist)
PLT.display_image(result)

In [ ]:
data_heat = json.dumps({"records": [
    {"row": "A", "col": "X", "val": 10},
    {"row": "A", "col": "Y", "val": 20},
    {"row": "B", "col": "X", "val": 30},
    {"row": "B", "col": "Y", "val": 40}
]})

result = PLT.plot_heat_map(values='val', index='row', columns='col', title='Heatmap', data=data_heat)
PLT.display_image(result)

In [ ]:
data_multi = json.dumps({"records": [
    {"group": "X", "metric1": 10, "metric2": 20},
    {"group": "Y", "metric1": 30, "metric2": 15},
    {"group": "Z", "metric1": 25, "metric2": 35}
]})

result = PLT.plot_multi_column_bar_graph(
    xLabel='group',
    value_vars=['metric1', 'metric2'],
    title='Multi Column Bar',
    data=data_multi
)
PLT.display_image(result)

#**10. Export Data**

In [ ]:
inspector.export_cleaned_data('cleaned_data.csv')